//------------------------------------------------------------------------------
// <auto-generated>
//     Αυτός ο κώδικας δημιουργήθηκε από εργαλείο.
//     Έκδοση χρόνου εκτέλεσης:4.0.30319.42000
//
//     Τυχόν αλλαγές σε αυτό το αρχείο ενδέχεται να προκαλέσουν εσφαλμένη συμπεριφορά και θα χαθούν αν
//     δημιουργηθεί ξανά ο κώδικας.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookApp {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Μια κλάση πόρων ισχυρού τύπου, για αναζήτηση μεταφρασμένων συμβολοσειρών κ.λπ.
    /// </summary>
    // Αυτή η κλάση δημιουργήθηκε αυτόματα από την κλάση StronglyTypedResourceBuilder
    // μέσω ενός εργαλείου όπως το ResGen ή το Visual Studio.
    // Για να προσθέσετε ή να καταργήσετε ένα μέλος, επεξεργαστείτε το αρχείο .ResX και στη συνέχεια εκτελέστε ξανά το ResGen
    // με την επιλογή /str ή επαναδομήστε το έργο VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Επιστρέφει την αποθηκευμένη στο cache παρουσία ResourceManager που χρησιμοποιείται από αυτή την κλάση.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CookApp.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Παρακάμπτει την ιδιότητα CurrentUICulture του τρέχοντος νήματος για όλες τις
        ///   αναζητήσεις πόρων που χρησιμοποιούν αυτή την κλάση πόρων με αυστηρά καθορισμένο τύπο.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Αναζήτηση μεταφρασμένης συμβολοσειράς παρόμοιας με το Προσθεστε νεο Υλικο.
        /// </summary>
        internal static string sAddNewIngredient {
            get {
                return ResourceManager.GetString("sAddNewIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Αναζήτηση μεταφρασμένης συμβολοσειράς παρόμοιας με το Τα Υλικα μου.
        /// </summary>
        internal static string sMyIngredients {
            get {
                return ResourceManager.GetString("sMyIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Αναζήτηση μεταφρασμένης συμβολοσειράς παρόμοιας με το Νεο Υλικο.
        /// </summary>
        internal static string sNewIngredient {
            get {
                return ResourceManager.GetString("sNewIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Αναζήτηση μεταφρασμένης συμβολοσειράς παρόμοιας με το Απόθήκευση Υλικού;.
        /// </summary>
        internal static string sStoreIngredient {
            get {
                return ResourceManager.GetString("sStoreIngredient", resourceCulture);
            }
        }
    }
}
